# Generated by Django 4.2.4 on 2023-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/default.webp', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='job_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
