# Generated by Django 4.2.4 on 2023-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chairman_pic_alter_societymember_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/default.webp', upload_to='media/images'),
        ),
    ]
