# Generated by Django 4.2.4 on 2023-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_societymember_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_titale', models.CharField(max_length=50)),
                ('notice_description', models.FileField(upload_to='')),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/image')),
            ],
        ),
    ]
