# Generated by Django 4.2.4 on 2023-09-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_titale',
            new_name='notice_title',
        ),
    ]
