# Generated by Django 4.2.4 on 2023-10-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_societymember_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
