# Generated by Django 4.2.4 on 2023-10-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_societymember_email_societymember_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymember',
            name='password',
        ),
    ]
