# Generated by Django 4.2.4 on 2023-11-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.IntegerField(max_length=50)),
                ('duedate', models.TextField(max_length=50)),
            ],
        ),
    ]
