# Generated by Django 4.2.4 on 2023-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employees_pic_hr_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_account_no',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_of_join',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='emergency_contact_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='emergency_contact_no',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='no_of_children',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='relationship',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='religion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='bank_account_no',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='bank_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='date_of_birth',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='date_of_join',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='designation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='emergency_contact_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='emergency_contact_no',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='no_of_children',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='relationship',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='religion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
