# Generated by Django 4.2.4 on 2023-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employees_age_employees_bank_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='pin_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='pin_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
