# Generated by Django 4.2.4 on 2023-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employees_country_employees_pin_code_employees_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='marital_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='marital_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
