# Generated by Django 4.2.4 on 2023-09-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hr_marital_status_alter_employees_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='family_member_birth_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='family_member_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='family_member_phone_no',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='family_member_relationship',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='family_member_birth_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='family_member_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='family_member_phone_no',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='family_member_relationship',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='no_of_children',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
