# Generated by Django 4.2.4 on 2023-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employees_family_member_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='institut_complate_date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='institut_degree_grade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='institut_degree_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='institut_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='institut_start_date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='institut_complate_date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='institut_degree_grade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='institut_degree_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='institut_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='institut_start_date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
