# Generated by Django 4.2.4 on 2023-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_employees_institut_complate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='date_of_join',
            field=models.DateTimeField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='institut_complate_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='institut_start_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
    ]
