# Generated by Django 4.2.4 on 2023-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chairman_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/dafault.webp', upload_to='media/images'),
        ),
    ]
